---
title: "Script 2: Differential gene expression analysis Active TB Blood"
---
Load libraries
```{r}
library(tidyverse)
#install.packages("devtools")
#devtools::install_github("PF2-pasteur-fr/SARTools", build_opts="--no-resave-data")
library(SARTools)
library(openxlsx)
```

Step 1: Prep input data for SARtools script
```{r}
# Load data
matrix <- read.csv("../../../data/ProcessedRaw_Blood_ActiveTB.csv")
matrix_int <- round(matrix[,2:ncol(matrix)]) # round to integer

genes <- as.data.frame(matrix[,1]) # list of gene identifiers
names <- colnames(matrix_int) # list of samples
dir.create("../../../data/BloodActiveTBraw") # new folder where single .txt files are saved to

# split raw data matrix into single .txt files
for (i in 1:length(names)){
  sample <- matrix_int[,i]
  merged <- cbind(genes,sample)
  write.table(merged,file=paste0("../../../data/BloodActiveTBraw/",names[i],".txt"),row.names=FALSE,col.names=FALSE,sep="\t")
}

# add filename to metadata and save as .txt file
meta <- read.csv("../../../data/Meta_Blood_ActiveTB.csv") %>%
  mutate(Filename = paste0(sample,".txt")) %>%
  dplyr::select(sample,Filename,sex,cluster)
write.table(meta,"../../../data/Meta_Blood_ActiveTB.txt",sep="\t",row.names = F)
```

Step 2: Prep parameters for SARtools analysis
SARtools template script from: https://github.com/PF2-pasteur-fr/SARTools/blob/master/template_script_DESeq2.r
```{r}
rm(list=ls())                                       # remove all the objects from the R session
workDir <- "../../../data"                          # working directory for the R session
projectName <- "Blood Active TB - Male vs Female"   # name of the project
author <- "Your name"                               # author of the statistical analysis/report
targetFile <- "Meta_Blood_ActiveTB.txt"             # path to the design/target file
rawDir <- "BloodActiveTBraw"                        # path to the directory containing raw counts files
featuresToRemove <- NULL                            # names of the features to be removed
                                                    # (specific HTSeq-count information and rRNA for example)                                            # NULL if no feature to remove
varInt <- "sex"                                     # factor of interest
condRef <- "Female"                                 # reference biological condition
batch <- "cluster"                                  # blocking factor: NULL (default) or "batch" for example
fitType <- "parametric"                             # mean-variance relationship: "parametric" (default), "local" or "mean"
cooksCutoff <- FALSE                                # TRUE/FALSE to perform the outliers detection (default is TRUE)
independentFiltering <- TRUE                        # TRUE/FALSE to perform independent filtering (default is TRUE)
alpha <- 0.05                                       # threshold of statistical significance
pAdjustMethod <- "fdr"                              # p-value adjustment method: "BH" (default) or "BY"

typeTrans <- "VST"                                  # transformation for PCA/clustering: "VST" or "rlog"
locfunc <- "median"                                 # "median" (default) or "shorth" to estimate the size factors

colors <- c("dodgerblue","firebrick1",              # vector of colors of each biological condition on the plots
            "MediumVioletRed","SpringGreen")

forceCairoGraph <- FALSE
```

Step 3: Run SARtools analysis
SARtools template script from: https://github.com/PF2-pasteur-fr/SARTools/blob/master/template_script_DESeq2.r
```{r}
setwd(workDir)

if (forceCairoGraph) options(bitmapType="cairo")

# checking parameters
checkParameters.DESeq2(projectName=projectName,author=author,targetFile=targetFile,
                       rawDir=rawDir,featuresToRemove=featuresToRemove,varInt=varInt,
                       condRef=condRef,batch=batch,fitType=fitType,cooksCutoff=cooksCutoff,
                       independentFiltering=independentFiltering,alpha=alpha,pAdjustMethod=pAdjustMethod,
                       typeTrans=typeTrans,locfunc=locfunc,colors=colors)

# loading target file
target <- loadTargetFile(targetFile=targetFile, varInt=varInt, condRef=condRef, batch=batch)

# convert batch/cluster column to a factor
target[[batch]] <- as.factor(target[[batch]])

# loading counts
counts <- loadCountData(target=target, rawDir=rawDir, featuresToRemove=featuresToRemove)

# description plots
#majSequences <- descriptionPlots(counts=counts, group=target[,varInt], col=colors)

# analysis with DESeq2
out.DESeq2 <- run.DESeq2(counts=counts, target=target, varInt=varInt, batch=batch,
                         locfunc=locfunc, fitType=fitType, pAdjustMethod=pAdjustMethod,
                         cooksCutoff=cooksCutoff, independentFiltering=independentFiltering, alpha=alpha)

# PCA + clustering
#exploreCounts(object=out.DESeq2$dds, group=target[,varInt], typeTrans=typeTrans, col=colors)

# summary of the analysis (boxplots, dispersions, diag size factors, export table, nDiffTotal, histograms, MA plot)
summaryResults <- summarizeResults.DESeq2(out.DESeq2, group=target[,varInt], col=colors,
                                          independentFiltering=independentFiltering,
                                          cooksCutoff=cooksCutoff, alpha=alpha)
# save image of the R session
#save.image(file=paste0(projectName, ".RData"))

# generating HTML report
#writeReport.DESeq2(target=target, counts=counts, out.DESeq2=out.DESeq2, summaryResults=summaryResults,
#                   majSequences=majSequences, workDir=workDir, projectName=projectName, author=author,
#                   targetFile=targetFile, rawDir=rawDir, featuresToRemove=featuresToRemove, varInt=varInt,
#                   condRef=condRef, batch=batch, fitType=fitType, cooksCutoff=cooksCutoff,
#                   independentFiltering=independentFiltering, alpha=alpha, pAdjustMethod=pAdjustMethod,
#                   typeTrans=typeTrans, locfunc=locfunc, colors=colors)
```

Step 4: Tidy output
```{r}
# move full results table to new directory to avoid overwriting by future SARtools runs
dir.create("../../../data/SARtools_output_BloodActiveTB")
file.rename("../../../data/tables/MalevsFemale.complete.txt","../../../data/SARtools_output_BloodActiveTB/MalevsFemale.complete.txt")

# save relevant output to source data file
dat <- read.table("../../../data/SARtools_output_BloodActiveTB/MalevsFemale.complete.txt", header = T)
source_dat <- dat %>%
  dplyr::select(Id,log2FoldChange,padj) %>%
  tidyr::drop_na(log2FoldChange, padj) %>%
  dplyr::rename(ensembl_gene_id = "Id")

wb <- loadWorkbook("../../../SourceData.xlsx")

addWorksheet(wb,"Fig1C")
writeData(wb, "Fig1C", source_dat)

saveWorkbook(wb, "../../../SourceData.xlsx", overwrite = TRUE)

```

